<a href="https://colab.research.google.com/github/Krish-s/Pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
df_store = pd.read_csv("/content/drive/MyDrive/Class notes/store sales dataset/stores_data_set.csv")
df_feature=pd.read_csv("/content/drive/MyDrive/Class notes/store sales dataset/Features_data_set.csv")
df_sales=pd.read_csv("/content/drive/MyDrive/Class notes/store sales dataset/sales_data_set.csv")

In [27]:
df_store

    Store Type    Size
0       1    A  151315
1       2    A  202307
2       3    B   37392
3       4    A  205863
4       5    B   34875
5       6    A  202505
6       7    B   70713
7       8    A  155078
8       9    B  125833
9      10    B  126512
10     11    A  207499
11     12    B  112238
12     13    A  219622
13     14    A  200898
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
18     19    A  203819
19     20    A  203742
20     21    B  140167
21     22    B  119557
22     23    B  114533
23     24    A  203819
24     25    B  128107
25     26    A  152513
26     27    A  204184
27     28    A  206302
28     29    B   93638
29     30    C   42988
30     31    A  203750
31     32    A  203007
32     33    A   39690
33     34    A  158114
34     35    B  103681
35     36    A   39910
36     37    C   39910
37     38    C   39690
38     39    A  184109
39     40    A  155083
40     41    A  196321
41     42    C   39690
42     43    C   41062
43     44    C   39910
44     45    B  118221

In [28]:
df_feature.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [29]:
df_sales.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [7]:
pip install pandasai

Collecting pandasai
  Downloading pandasai-2.4.0-py3-none-any.whl.metadata (11 kB)
Collecting astor<0.9.0,>=0.8.1 (from pandasai)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: duckdb<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pandasai) (1.1.3)
Collecting faker<20.0.0,>=19.12.0 (from pandasai)
  Downloading Faker-19.13.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: jinja2<4.0.0,>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from pandasai) (3.1.4)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in /usr/local/lib/python3.10/dist-packages (from pandasai) (3.8.0)
Requirement already satisfied: openai<2 in /usr/local/lib/python3.10/dist-packages (from pandasai) (1.54.4)
Collecting pandas==1.5.3 (from pandasai)
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pillow<11.0.0,>=10.1.0 (from pandasai)
  Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.10/dist-packages (from pandasai) (2.9.2)
Collecting python-dotenv<2.0.0,>=1.0.0 (from pandasai)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from pandasai) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from pandasai) (1.13.1)
Requirement already satisfied: sqlalchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from pandasai) (2.0.36)
Requirement already satisfied: sqlglot<26.0.0,>=25.0.3 in /usr/local/lib/python3.10/dist-packages (from sqlglot[rs]<26.0.0,>=25.0.3->pandasai) (25.1.0)
Collecting torch==2.4.1 (from pandasai)
  Downloading torch-2.4.1-cp310-cp310-manylinux1_x86_64.whl.metadata (26 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.3->pandasai) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.3->pandasai) (2024.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.3->pandasai) (1.26.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.4.1->pandasai) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.4.1->pandasai) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch==2.4.1->pandasai) (1.13.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch==2.4.1->pandasai) (3.4.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch==2.4.1->pandasai) (2024.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.4.1->pandasai)
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.4.1->pandasai)
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.4.1->pandasai)
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch==2.4.1->pandasai)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.4.1->pandasai)
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.4.1->pandasai)
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.4.1->pandasai)
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.4.1->pandasai)
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.4.1->pandasai)
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.4.1->pandasai)
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.4.1->pandasai)
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.0.0 (from torch==2.4.1->pandasai)
  Downloading triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.4.1->pandasai) (12.6.77)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<4.0.0,>=3.1.3->pandasai) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (4.55.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (3.2.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (0.27.2)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (0.7.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai<2->pandasai) (4.66.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->pandasai) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=1->pandasai) (2.23.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (2024.8.30)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<3,>=1.4->pandasai) (3.1.1)
Collecting sqlglotrs==0.2.6 (from sqlglot[rs]<26.0.0,>=25.0.3->pandasai)
  Downloading sqlglotrs-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (258 bytes)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai<2->pandasai) (1.2.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai<2->pandasai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2->pandasai) (0.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas==1.5.3->pandasai) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch==2.4.1->pandasai) (1.3.0)
Downloading pandasai-2.4.0-py3-none-any.whl (193 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.4/193.4 kB 5.0 MB/s eta 0:00:00
Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 79.0 MB/s eta 0:00:00
Downloading torch-2.4.1-cp310-cp310-manylinux1_x86_64.whl (797.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.1/797.1 MB 1.3 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 43.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 40.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 34.6 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.4 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.1 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.0 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 6.2 MB/s eta 0:00:00
Downloading triton-3.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (209.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.4/209.4 MB 6.3 MB/s eta 0:00:00
Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Downloading Faker-19.13.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 58.7 MB/s eta 0:00:00
Downloading pillow-10.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 82.8 MB/s eta 0:00:00
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading sqlglotrs-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 44.8 MB/s eta 0:00:00
Installing collected packages: triton, sqlglotrs, python-dotenv, pillow, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, astor, pandas, nvidia-cusolver-cu12, nvidia-cudnn-cu12, faker, torch, pandasai
  Attempting uninstall: pillow
    Found existing installation: pillow 11.0.0
    Uninstalling pillow-11.0.0:
      Successfully uninstalled pillow-11.0.0
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.23.4
    Uninstalling nvidia-nccl-cu12-2.23.4:
      Successfully uninstalled nvidia-nccl-cu12-2.23.4
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4
    Uninstalling nvidia-cufft-cu12-11.3.0.4:
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.3.3
    Uninstalling nvidia-cublas-cu12-12.6.3.3:
      Successfully uninstalled nvidia-cublas-cu12-12.6.3.3
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.5.1.17
    Uninstalling nvidia-cudnn-cu12-9.5.1.17:
      Successfully uninstalled nvidia-cudnn-cu12-9.5.1.17
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1+cu121
    Uninstalling torch-2.5.1+cu121:
      Successfully uninstalled torch-2.5.1+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.10.1 requires pandas<2.2.3dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 1.5.3 which is incompatible.
mizani 0.13.0 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
plotnine 0.14.1 requires pandas>=2.2.0, but you have pandas 1.5.3 which is incompatible.
torchaudio 2.5.1+cu121 requires torch==2.5.1, but you have torch 2.4.1 which is incompatible.
torchvision 0.20.1+cu121 requires torch==2.5.1, but you have torch 2.4.1 which is incompatible.
xarray 2024.10.0 requires pandas>=2.1, but you have pandas 1.5.3 which is incompatible.
Successfully installed astor-0.8.1 faker-19.13.0 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvtx-cu12-12.1.105 pandas-1.5.3 pandasai-2.4.0 pillow-10.4.0 python-dotenv-1.0.1 sqlglotrs-0.2.6 torch-2.4.1 triton-3.0.0

In [4]:
import os
os.environ["PANDASAI_API_KEY"]="$2a$10$XtC584efQne6aywU8lbWsOKYEJdZAvU/v3oKJjLsgsSBuVRrM/6.q"

In [30]:
df_store_sales = pd.merge(df_sales,df_store,on="Store")
df_feature.drop(columns ="IsHoliday",axis = 1,inplace = True)
df_final = pd.merge(df_store_sales,df_feature,on = ["Store","Date"])

In [31]:
df_final.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,1,05/02/2010,24924.50,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
1,1,2,05/02/2010,50605.27,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
2,1,3,05/02/2010,13740.12,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
3,1,4,05/02/2010,39954.04,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106
4,1,5,05/02/2010,32229.38,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106

In [7]:
from pandasai import SmartDataframe

In [8]:
sdf = SmartDataframe(df_final)

In [9]:
sdf.chat("return average Customer visit in type C store in april month")

<string>:2: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.

4166.0

In [11]:
print(sdf.last_code_generated)

df = pd.concat(dfs)
df['Date'] = pd.to_datetime(df['Date'])
df_filtered = df[(df['Date'].dt.month >= 1) & (df['Date'].dt.month <= 5)]
result = df_filtered.groupby('Dept')['Weekly_Sales'].sum().reset_index()
result_dict = {'type': 'dataframe', 'value': result}
result_dict

## task 1 To do solve the following questions ##

In [ ]:
  TASK

1.)Identify average customer visit in Type C store in April Month.

2.)Find the highest sales in each store type on Holiday season.

3.)What is the expected sales of each depeartment when the unemployment factor is greater than 7.

4.)Aggregate net sales for each department in month wise.

5.)Identify the performance of the store on weekwise, without offers.

In [34]:
df_final["Date"]=pd.to_datetime(df_final["Date"],format = "%d/%m/%Y")

In [35]:
df_final["day"]=df_final["Date"].dt.day
df_final["month"]=df_final["Date"].dt.month
df_final["Year"]=df_final["Date"].dt.year
df_final["day_of_week"]=df_final["Date"].dt.day_of_week
df_final["week"] = df_final["Date"].dt.isocalendar().week

In [37]:
df_final

,Store,Dept,Date,Weekly_Sales,IsHoliday,Type,Size,Temperature,Fuel_Price,MarkDown1,...,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,day,month,Year,day_of_week,week
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,NaN,...,NaN,NaN,NaN,211.096358,8.106,5,2,2010,4,5
1,1,2,2010-02-05,50605.27,False,A,151315,42.31,2.572,NaN,...,NaN,NaN,NaN,211.096358,8.106,5,2,2010,4,5
2,1,3,2010-02-05,13740.12,False,A,151315,42.31,2.572,NaN,...,NaN,NaN,NaN,211.096358,8.106,5,2,2010,4,5
3,1,4,2010-02-05,39954.04,False,A,151315,42.31,2.572,NaN,...,NaN,NaN,NaN,211.096358,8.106,5,2,2010,4,5
4,1,5,2010-02-05,32229.38,False,A,151315,42.31,2.572,NaN,...,NaN,NaN,NaN,211.096358,8.106,5,2,2010,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,93,2012-10-26,2487.80,False,B,118221,58.85,3.882,4018.91,...,100.0,211.94,858.33,192.308899,8.667,26,10,2012,4,43
421566,45,94,2012-10-26,5203.31,False,B,118221,58.85,3.882,4018.91,...,100.0,211.94,858.33,192.308899,8.667,26,10,2012,4,43
421567,45,95,2012-10-26,56017.47,False,B,118221,58.85,3.882,4018.91,...,100.0,211.94,858.33,192.308899,8.667,26,10,2012,4,43
421568,45,97,2012-10-26,6817.48,False,B,118221,58.85,3.882,4018.91,...,100.0,211.94,858.33,192.308899,8.667,26,10,2012,4,43
421569,45,98,2012-10-26,1076.80,False,B,118221,58.85,3.882,4018.91,...,100.0,211.94,858.33,192.308899,8.667,26,10,2012,4,43

## Task 2 to print ind vs aus match score card ##

In [38]:
train = pd.read_csv("/content/drive/MyDrive/Class notes/Datascience_dataset/train-chennai-sale.csv")

In [39]:
train

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,...,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,...,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,...,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,...,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,...,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [41]:
pd.set_option("display.max_columns",None)

In [42]:
train.head()

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,15-05-1967,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,22-12-1995,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,09-02-1992,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,18-03-1988,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,13-10-1979,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250

In [40]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PRT_ID         7109 non-null   object
 1   AREA           7109 non-null   object
 2   INT_SQFT       7109 non-null   int64
 3   DATE_SALE      7109 non-null   object
 4   DIST_MAINROAD  7109 non-null   int64
 5   N_BEDROOM      7108 non-null   float64
 6   N_BATHROOM     7104 non-null   float64
 7   N_ROOM         7109 non-null   int64
 8   SALE_COND      7109 non-null   object
 9   PARK_FACIL     7109 non-null   object
 10  DATE_BUILD     7109 non-null   object
 11  BUILDTYPE      7109 non-null   object
 12  UTILITY_AVAIL  7109 non-null   object
 13  STREET         7109 non-null   object
 14  MZZONE         7109 non-null   object
 15  QS_ROOMS       7109 non-null   float64
 16  QS_BATHROOM    7109 non-null   float64
 17  QS_BEDROOM     7109 non-null   float64
 18  QS_OVERALL     7061 non-null   float64
 19  REG_FEE        7109 non-null   int64
 20  COMMIS         7109 non-null   int64
 21  SALES_PRICE    7109 non-null   int64
dtypes: float64(6), int64(6), object(10)
memory usage: 1.2+ MB

In [43]:
train.columns

Index(['PRT_ID', 'AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'REG_FEE', 'COMMIS',
       'SALES_PRICE'],
      dtype='object')

In [44]:
train["AREA"].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Karapakam',
       'Ana Nagar', 'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar',
       'KKNagar'], dtype=object)

In [45]:
train["AREA"] = train["AREA"].apply(lambda i: "Karapakkam" if (i== "Karapakam") else i)

In [47]:
train["AREA"].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Ana Nagar',
       'Chormpet', 'Adyr', 'Velchery', 'Ann Nagar', 'KKNagar'],
      dtype=object)

In [48]:
train["AREA"]= train["AREA"].apply(lambda i : "Anna Nagar" if (i=="Ana Nagar") or (i=="Ann Nagar") else i)

In [49]:
train["AREA"].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'TNagar', 'T Nagar', 'Chrompt', 'Chrmpet', 'Chormpet',
       'Adyr', 'Velchery', 'KKNagar'], dtype=object)

In [50]:
train["AREA"]= train["AREA"].apply(lambda i : "Adyar" if (i=="Adyr")else i)
train["AREA"]= train["AREA"].apply(lambda i : "Chrompet" if (i=="Chrompt" or i=="Chrmpet" or i == "Chormpet")else i)
train["AREA"] = train["AREA"].apply(lambda i :"Velachery" if (i=="Velchery")else i)
train["AREA"]= train["AREA"].apply(lambda i : "KK Nagar" if (i=="KKNagar")else i)
train["AREA"]= train["AREA"].apply(lambda i : "T Nagar" if (i=="TNagar") else i)

In [52]:
train["AREA"].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [54]:
train["DATE_SALE"]=pd.to_datetime(train["DATE_SALE"],format = "%d-%m-%Y")
train["DATE_BUILD"] = pd.to_datetime(train["DATE_BUILD"],format ="%d-%m-%Y")

In [55]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PRT_ID         7109 non-null   object
 1   AREA           7109 non-null   object
 2   INT_SQFT       7109 non-null   int64
 3   DATE_SALE      7109 non-null   datetime64[ns]
 4   DIST_MAINROAD  7109 non-null   int64
 5   N_BEDROOM      7108 non-null   float64
 6   N_BATHROOM     7104 non-null   float64
 7   N_ROOM         7109 non-null   int64
 8   SALE_COND      7109 non-null   object
 9   PARK_FACIL     7109 non-null   object
 10  DATE_BUILD     7109 non-null   datetime64[ns]
 11  BUILDTYPE      7109 non-null   object
 12  UTILITY_AVAIL  7109 non-null   object
 13  STREET         7109 non-null   object
 14  MZZONE         7109 non-null   object
 15  QS_ROOMS       7109 non-null   float64
 16  QS_BATHROOM    7109 non-null   float64
 17  QS_BEDROOM     7109 non-null   float64
 18  QS_OVERALL     7061 non-null   float64
 19  REG_FEE        7109 non-null   int64
 20  COMMIS         7109 non-null   int64
 21  SALES_PRICE    7109 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(6), object(8)
memory usage: 1.2+ MB

In [57]:
train.set_index("PRT_ID",inplace = True)

In [58]:
train.head()

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Others,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,Others,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250

In [ ]:
for i in train.select_dtypes(include = "object").columns

In [67]:
for i in train.select_dtypes(include = ["object"]).columns:
  print(i,train[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale' 'Ab Normal'
 'Partiall' 'Adj Land' 'PartiaLl']
PARK_FACIL ['Yes' 'No' 'Noo']
BUILDTYPE ['Commercial' 'Others' 'Other' 'House' 'Comercial']
UTILITY_AVAIL ['AllPub' 'ELO' 'NoSewr ' 'NoSeWa' 'All Pub']
STREET ['Paved' 'Gravel' 'No Access' 'Pavd' 'NoAccess']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [73]:
train["SALE_COND"] = train["SALE_COND"].apply(lambda i: "AbNormal" if (i=="Ab Normal")else i)
train["SALE_COND"] = train ["SALE_COND"].apply(lambda i : "Partial" if (i=="Partiall" or i =="PartiaLl")else i)
train["SALE_COND"] = train["SALE_COND"].apply(lambda i : "AdjLand" if (i=="Adj Land")else i)
train["PARK_FACIL"] = train["PARK_FACIL"].apply(lambda i : "No" if (i == "Noo") else i)
train["BUILDTYPE"]  = train["BUILDTYPE"].apply(lambda i : "Commercial" if (i=="Comercial")else i)
train["BUILDTYPE"] = train["BUILDTYPE"].apply(lambda i : "Other" if (i=="Others") else i)
train["UTILITY_AVAIL"] =train["UTILITY_AVAIL"].apply(lambda i: "AllPub" if (i=="All Pub")else i)
train["UTILITY_AVAIL"] = train["UTILITY_AVAIL"].apply(lambda i : "No Sewage" if (i=="NoSewr" or i=="NoSeWa" or i =="NoSewr ")else i)
train["STREET"] = train["STREET"].apply(lambda i: "Paved" if (i=="Pavd") else i)
train["STREET"] = train["STREET"].apply(lambda i : "No Access" if (i=="NoAccess")else i)

In [74]:
for i in train.select_dtypes(include=["object"]).columns :
  print(i,train[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
PARK_FACIL ['Yes' 'No']
BUILDTYPE ['Commercial' 'Other' 'House']
UTILITY_AVAIL ['AllPub' 'ELO' 'No Sewage']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [75]:
train1 = train.copy()

In [80]:
train["PARK_FACIL"]=train["PARK_FACIL"].replace({"Yes":1})

In [81]:
train

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,Other,No Sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1,1979-10-13,Other,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,Other,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1,1995-04-11,Other,No Sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,House,No Sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1,1961-07-24,Other,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [85]:
train = train1.copy()

In [87]:
train["PARK_FACIL"]=train["PARK_FACIL"].map({"Yes":1})

In [88]:
train

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1.0,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,NaN,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1.0,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,NaN,1988-03-18,Other,No Sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1.0,1979-10-13,Other,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,NaN,1962-01-15,Other,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1.0,1995-04-11,Other,No Sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,NaN,1978-09-01,House,No Sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1.0,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1.0,1961-07-24,Other,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [97]:
train=train1.copy()

In [94]:
train["PARK_FACIL"]=train["PARK_FACIL"].map({"Yes":1,"No":0})

In [95]:
train

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,0,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,0,1988-03-18,Other,No Sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1,1979-10-13,Other,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,0,1962-01-15,Other,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1,1995-04-11,Other,No Sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,0,1978-09-01,House,No Sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1,1961-07-24,Other,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [98]:
from sklearn.preprocessing import OrdinalEncoder

In [99]:
encode = OrdinalEncoder()

In [101]:
train["PARK_FACIL"]=encode.fit_transform(train[["PARK_FACIL"]])

In [102]:
train

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1.0,1967-05-15,Commercial,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,0.0,1995-12-22,Commercial,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1.0,1992-02-09,Commercial,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,0.0,1988-03-18,Other,No Sewage,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1.0,1979-10-13,Other,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,0.0,1962-01-15,Other,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1.0,1995-04-11,Other,No Sewage,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,0.0,1978-09-01,House,No Sewage,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1.0,1977-08-11,Commercial,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1.0,1961-07-24,Other,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [103]:
for i in train.select_dtypes(include = ["object"]).columns:
  print(i,train[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
BUILDTYPE ['Commercial' 'Other' 'House']
UTILITY_AVAIL ['AllPub' 'ELO' 'No Sewage']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [104]:
for i in train.select_dtypes(include=["object"]).columns:
  train[i]=encode.fit_transform(train[[i]])

In [105]:
for i in train.select_dtypes(include = ["object"]).columns:
  print(i,train[i].unique())

In [106]:
train

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,BUILDTYPE,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,4.0,1004,2011-05-04,131,1.0,1.0,3,0.0,1.0,1967-05-15,0.0,0.0,2.0,0.0,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,1.0,1986,2006-12-19,26,2.0,1.0,5,0.0,0.0,1995-12-22,0.0,0.0,0.0,3.0,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,0.0,909,2012-02-04,70,1.0,1.0,3,0.0,1.0,1992-02-09,0.0,1.0,0.0,4.0,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,6.0,1855,2010-03-13,14,3.0,2.0,5,2.0,0.0,1988-03-18,2.0,2.0,2.0,2.0,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,4.0,1226,2009-10-05,84,1.0,1.0,3,0.0,1.0,1979-10-13,2.0,0.0,0.0,1.0,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,4.0,598,2011-01-03,51,1.0,1.0,2,1.0,0.0,1962-01-15,2.0,1.0,1.0,5.0,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,6.0,1897,2004-04-08,52,3.0,2.0,5,2.0,1.0,1995-04-11,2.0,2.0,1.0,3.0,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,6.0,1614,2006-08-25,152,2.0,1.0,4,3.0,0.0,1978-09-01,1.0,2.0,0.0,2.0,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,4.0,787,2009-08-03,40,1.0,1.0,2,4.0,1.0,1977-08-11,0.0,1.0,2.0,4.0,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,6.0,1896,2005-07-13,156,3.0,2.0,5,4.0,1.0,1961-07-24,2.0,1.0,2.0,2.0,3.1,3.5,4.3,3.640,349177,79812,9976480

In [107]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7109 entries, P03210 to P09794
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           7109 non-null   float64
 1   INT_SQFT       7109 non-null   int64
 2   DATE_SALE      7109 non-null   datetime64[ns]
 3   DIST_MAINROAD  7109 non-null   int64
 4   N_BEDROOM      7108 non-null   float64
 5   N_BATHROOM     7104 non-null   float64
 6   N_ROOM         7109 non-null   int64
 7   SALE_COND      7109 non-null   float64
 8   PARK_FACIL     7109 non-null   float64
 9   DATE_BUILD     7109 non-null   datetime64[ns]
 10  BUILDTYPE      7109 non-null   float64
 11  UTILITY_AVAIL  7109 non-null   float64
 12  STREET         7109 non-null   float64
 13  MZZONE         7109 non-null   float64
 14  QS_ROOMS       7109 non-null   float64
 15  QS_BATHROOM    7109 non-null   float64
 16  QS_BEDROOM     7109 non-null   float64
 17  QS_OVERALL     7061 non-null   float64
 18  REG_FEE        7109 non-null   int64
 19  COMMIS         7109 non-null   int64
 20  SALES_PRICE    7109 non-null   int64
dtypes: datetime64[ns](2), float64(13), int64(6)
memory usage: 1.4+ MB